# Generated by Django 2.2.6 on 2019-11-01 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat2',
            field=models.IntegerField(blank=True, default=2),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat3',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat_turn',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse',
            field=models.IntegerField(blank=True, default=59),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mouse_user_foreign_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
