# Generated by Django 2.2.6 on 2019-11-01 18:30

import datamodel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0005_auto_20191101_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mouse_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mouse_user_foreign_key', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=datamodel.models.GameStatus(blank=True, choices=[(0, 'Created'), (1, 'Active'), (2, 'Finished')], default=0),
        ),
    ]
