# Generated by Django 2.2.6 on 2019-11-01 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_auto_20191101_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mouse_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mouse_user_foreign_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
