# Generated by Django 2.2.6 on 2019-11-01 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0008_auto_20191101_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mouse_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mouse_user_foreign_key', to=settings.AUTH_USER_MODEL),
        ),
    ]
