# Generated by Django 2.2.6 on 2019-11-01 22:25

import datamodel.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0012_auto_20191101_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=datamodel.models.GameStatus(blank=True, choices=[(0, 0), (1, 1), (2, 2)]),
        ),
    ]
