# Generated by Django 2.2.6 on 2019-11-09 15:06

import datamodel.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0014_auto_20191102_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cat1',
            field=models.IntegerField(blank=True, default=0, validators=[datamodel.models.Game.validator_tile]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat2',
            field=models.IntegerField(blank=True, default=2, validators=[datamodel.models.Game.validator_tile]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat3',
            field=models.IntegerField(blank=True, default=4, validators=[datamodel.models.Game.validator_tile]),
        ),
        migrations.AlterField(
            model_name='game',
            name='cat4',
            field=models.IntegerField(blank=True, default=6, validators=[datamodel.models.Game.validator_tile]),
        ),
        migrations.AlterField(
            model_name='game',
            name='mouse',
            field=models.IntegerField(blank=True, default=59, validators=[datamodel.models.Game.validator_tile]),
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='datamodel.Game'),
        ),
        migrations.AlterField(
            model_name='move',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to=settings.AUTH_USER_MODEL),
        ),
    ]
